
USE [master]
GO

/****** Object:  Database [StockMarketAnalyzerDB]    Script Date: 10/14/2016 09:08:25 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'StockMarketAnalyzerDB')
DROP DATABASE [StockMarketAnalyzerDB]
GO

USE [master]
GO

/****** Object:  Database [StockMarketAnalyzerDB]    Script Date: 10/14/2016 09:08:25 ******/
CREATE DATABASE [StockMarketAnalyzerDB] ON  PRIMARY 
( NAME = N'StockMarketAnalyzerDB', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\StockMarketAnalyzerDB.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'StockMarketAnalyzerDB_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\StockMarketAnalyzerDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StockMarketAnalyzerDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET ANSI_NULLS OFF
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET ANSI_PADDING OFF
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET ARITHABORT OFF
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET AUTO_CREATE_STATISTICS ON
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET  DISABLE_BROKER
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET  READ_WRITE
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET RECOVERY SIMPLE
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET  MULTI_USER
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [StockMarketAnalyzerDB] SET DB_CHAINING OFF
GO
